inc := -Isrc
lib := -lglew32 -lglfw -lopengl32 -lpng -lz
def := -DGLEW_STATIC -DWIN32 -DDEBUG
opt := -g
cxx := g++

modules := . Game Graphics System
src-dir := $(addprefix src/,$(modules))

src := $(foreach sdir,$(src-dir),$(wildcard $(sdir)/*.cpp))
obj := $(patsubst src/%.cpp,build/%.o,$(src))
dep := $(patsubst src/%.cpp,build/%.d,$(src))

help:
	@echo Name targets.

all: $(obj)
	$(cxx) -o build/G13.exe $(obj) $(lib)

include $(dep)

# dep-rule(module)
define dep-rule
build/$1/%.d: src/$1/%.cpp
	$(cxx) -M $(inc) $(def) $$< > $$@.$$$$; \
	sed 's,\($*\)\.o[ :]*,\1.o $$@ : ,g' < $$@.$$$$ > $$@; \
	rm -f $$@.$$$$
endef

# obj-rule(module)
define obj-rule
build/$1/%.o: src/$1/%.cpp
	$(cxx) -o $$@ -c $$< $(lib) $(inc) $(def) $(opt)
endef

$(foreach module,$(modules),$(eval $(call dep-rule,$(module))))
$(foreach module,$(modules),$(eval $(call obj-rule,$(module))))
